ТЗ 13
okbascreed/java-shareit pull request #1
Opened 2023-04-07 16:28 UTC by okbascreed

First review

2023-04-07 21:43 UTC, db-exp requested changes

2023-04-07 21:43 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    String name;
лучше еще размер поставить через Size

2023-04-07 21:43 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    String description;
лучше еще размер поставить через Size

2023-04-07 21:43 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/model/UserDto.java
> +    private String email;
лучше еще размер поставить через Size

2023-04-07 21:43 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +public class InMemoryUserStorage implements UserStorage {
Вместо Component тут лучше использовать Repository

2023-04-07 21:43 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +public class InMemoryItemStorage implements ItemStorage {
Вместо Component тут лучше использовать Repository

2023-04-07 21:43 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private void userValidation(UserDto userDto) {
можно сделать через кастомную аннотацию
https://blog.clairvoyantsoft.com/spring-boot-creating-a-custom-annotation-for-validation-edafbf9a97a4

2023-04-08 07:31 UTC, okbascreed commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    String name;
Благодарю, добавил!

2023-04-08 07:31 UTC, okbascreed commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    String description;
Благодарю, добавил!

2023-04-08 07:31 UTC, okbascreed commented on src/main/java/ru/practicum/shareit/user/model/UserDto.java
> +    private String email;
Благодарю, добавил!

2023-04-08 07:32 UTC, okbascreed commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +public class InMemoryUserStorage implements UserStorage {
Исправил.

2023-04-08 07:32 UTC, okbascreed commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +public class InMemoryItemStorage implements ItemStorage {
Исправил.

2023-04-08 07:34 UTC, okbascreed commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private void userValidation(UserDto userDto) {
Сделал через аннотация Lombok, добавив @NonNull к полям User, метод userValidation полностью исключил.
Благодарю, думаю, что стало более читаемо.

2023-04-08 19:41 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @NonNull
если NotBlank уже NonNull
https://struchkov.dev/blog/ru/spring-boot-validation/

2023-04-08 19:41 UTC, db-exp approved these changes

2023-05-15 16:12 UTC, merged